language: ruby

cache:
  - bundler
  - apt
  
env:
  global:
    secure: "XBu5eJYPG58gw/t6pNEAE7+f23lOds5hs46UNsW2KNPcVOrALjNBMk7fPjWHG2DwZoYCzNOsBsN53JjZQY8+DO5FKg1AH4/MS7NhAAsYL5V53ODsuL6BTTjgInOMNUwonOnB7CgVnyAC/nasFZYSSAm+B0QcusDhAMU1w09pqHA="

matrix:
  fast_finish: true
  
branches:
  only:
    - master


  
script:
  - chmod u+x *.sh . -R
  - ./test0.sh
#  - ./test.sh
